### ISSUE TITLE
All time open permission page when user select while in use startLocationService not working

### ISSUE THREAD

**Issue by urvashiN1608** [BWMuller/background_location#1]
MissingPluginException(No implementation found for method start_location_service on channel com.almoullim.background_location/methods)

Uncaught exception in binary message listener
E/DartMessenger(15342): java.lang.Exception: Permissions missing from location
E/DartMessenger(15342): 	at com.almoullim.background_location.BackgroundLocationService.onMethodCall(BackgroundLocationService.kt:203)
E/DartMessenger(15342): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/DartMessenger(15342): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/DartMessenger(15342): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/DartMessenger(15342): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/DartMessenger(15342): 	at android.os.Handler.handleCallback(Handler.java:958)
E/DartMessenger(15342): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/DartMessenger(15342): 	at android.os.Looper.loopOnce(Looper.java:222)
E/DartMessenger(15342): 	at android.os.Looper.loop(Looper.java:314)
E/DartMessenger(15342): 	at android.app.ActivityThread.main(ActivityThread.java:8670)
E/DartMessenger(15342): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(15342): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
E/DartMessenger(15342): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)

**Comment by BWMuller** [comment]
@urvashiN1608 The latest version should not instead of throwing the method not found error, correctly return with permissions missing error instead. 

Note the current library required the background location permissions, but the aim is to have that only be required if the config defined background callback support. Not sure when I'll be able to make that change though
